import { Layout } from '../../components/Layout/Main'

const PrivacyPolicyPage = () => (
  <Layout title='Políticas de Privacidad - Bauztel'>
    <section>
      <h1>Políticas de Privacidad</h1>
      <p>Actualizado el 10 julio de 2022</p>
    </section>
    <section>
      <p>
        Bauztel (“we,” “our,” or “us”) is committed to protecting your privacy.
        This Privacy Policy explains how your personal information is collected,
        used, and disclosed by Bauztel. This Privacy Policy applies to our
        website, https://bauztel.com, and its associated subdomains
        (collectively, our “Service”) alongside our application, Bauztel. By
        accessing or using our Service, you signify that you have read,
        understood, and agree to our collection, storage, use, and disclosure of
        your personal information as described in this Privacy Policy and our
        Terms of Service.
      </p>
      <h2>Definitions and key terms</h2>
      <p>
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, are strictly defined as:
        Cookie: small amount of data generated by a website and saved by your
        web browser. It is used to identify your browser, provide analytics,
        remember information about you such as your language preference or login
        information. Company: when this policy mentions “Company,” “we,” “us,”
        or “our,” it refers to Bauztel that is responsible for your information
        under this Privacy Policy. Customer: refers to the company, organization
        or person that signs up to use the Bauztel Service to manage the
        relationships with your consumers or service users. Device: any internet
        connected device such as a phone, tablet, computer or any other device
        that can be used to visit Bauztel and use the services. Personal Data:
        any information that directly, indirectly, or in connection with other
        information — including a personal identification number — allows for
        the identification or identifiability of a natural person. Service:
        refers to the service provided by Bauztel as described in the relative
        terms (if available) and on this platform. Third-party service: refers
        to advertisers, contest sponsors, promotional and marketing partners,
        and others who provide our content or whose products or services we
        think may interest you. Website: Bauztel’s site, which can be accessed
        via this URL: https://bauztel.com You: a person or entity that is
        registered with Bauztel to use the Services.
      </p>
      <h2>How do we use the information we collect?</h2>
      <p>
        Any of the information we collect from you may be used in one of the
        following ways: To personalize your experience (your information helps
        us to better respond to your individual needs) To improve our website
        (we continually strive to improve our website offerings based on the
        information and feedback we receive from you) To improve customer
        service (your information helps us to more effectively respond to your
        customer service requests and support needs) To process transactions To
        administer a contest, promotion, survey or other site feature To send
        periodic emails
      </p>
      <h2>How do we use your email address?</h2>
      <p>
        By submitting your email address on this website, you agree to receive
        emails from us. You can cancel your participation in any of these email
        lists at any time by clicking on the opt-out link or other unsubscribe
        option that is included in the respective email. We only send emails to
        people who have authorized us to contact them, either directly, or
        through a third party. We do not send unsolicited commercial emails,
        because we hate spam as much as you do. By submitting your email
        address, you also agree to allow us to use your email address for
        customer audience targeting on sites like Facebook, where we display
        custom advertising to specific people who have opted-in to receive
        communications from us. Email addresses submitted only through the order
        processing page will be used for the sole purpose of sending you
        information and updates pertaining to your order. If, however, you have
        provided the same email to us through another method, we may use it for
        any of the purposes stated in this Policy. Note: If at any time you
        would like to unsubscribe from receiving future emails, we include
        detailed unsubscribe instructions at the bottom of each email.
      </p>
      <h2>How long do we keep your information?</h2>
      <p>
        We keep your information only so long as we need it to provide Termify
        to you and fulfill the purposes described in this policy. This is also
        the case for anyone that we share your information with and who carries
        out services on our behalf. When we no longer need to use your
        information and there is no need for us to keep it to comply with our
        legal or regulatory obligations, we’ll either remove it from our systems
        or depersonalize it so that we cant identify you.
      </p>
    </section>
  </Layout>
)

export default PrivacyPolicyPage
